admin_user:
    pattern:  /
    defaults: { _controller: "UserBundle:User:index" }

admin_user_show:
    pattern:  /{id}/show
    defaults: { _controller: "UserBundle:User:show" }

admin_user_new:
    pattern:  /new
    defaults: { _controller: "UserBundle:User:new" }

admin_user_create:
    pattern:  /create
    defaults: { _controller: "UserBundle:User:create" }
    requirements: { _method: post }

admin_user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UserBundle:User:edit" }

admin_user_update:
    pattern:  /{id}/update
    defaults: { _controller: "UserBundle:User:update" }
    requirements: { _method: post }

admin_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UserBundle:User:delete" }
    requirements: { _method: post }
    
admin_user_activation:
    pattern:  /activation
    defaults: { _controller: "UserBundle:User:activation" }
    requirements: { _method: post }
