<?php

namespace FeodBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AmorcageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmorcageRepository extends EntityRepository
{

    public function countAll(){
        $count = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM FeodBundle:Amorcage a')
            ->getSingleScalarResult();
        return $count;
    }
    
    /**
    * Retourne le nombre de fiche par statut
    *
    * 0 : modification ou création
    * 1 : attente de vérification
    * 2 : attente de validation
    * 3 : validée
    *
    */
    public function countByStatut($statut)
    {
        $count = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM FeodBundle:Amorcage a
                WHERE a.statut = :statut')
            ->setParameter('statut', $statut)
            ->getSingleScalarResult();
        return $count;
    }

    public function findLast($i)
    {
        $result = $this->getEntityManager()
            ->createQuery('SELECT a FROM FeodBundle:Amorcage a
                WHERE a.statut = 3 ORDER BY a.dateMAJ DESC')
            ->setMaxResults($i)
            ->getResult();

        return $result;
    }

    public function countLastMonth()
    {
        $month=new \Datetime();
        $month->sub(new \DateInterval('P1M'));
        $result = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM FeodBundle:Amorcage a
                WHERE a.dateMAJ <= :auj AND a.dateMAJ > :month')
            ->setParameter('auj', new \Datetime())
            ->setParameter('month', $month)
            ->getSingleScalarResult();

        return $result;
    }



    public function searchByNomAndType($nomine, $type)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb -> select('m')
            -> from('FeodBundle:'.ucfirst($type), 'm');

        if ($nomine != null) {
            $qb -> andWhere('LOCATE(UPPER(:expression),UPPER(m.id)) != 0
                OR LOCATE(UPPER(:expression),UPPER(m.nomine)) != 0
                OR LOCATE(UPPER(:expression),UPPER(m.alias)) != 0
                OR LOCATE(UPPER(:expression),UPPER(m.denominationOTAN)) != 0
                OR LOCATE(UPPER(:expression),UPPER(m.designation)) != 0')
                -> setParameter('expression', $nomine);
        }

        return $qb->getQuery()
            ->getResult();
    }

    public function searchByAll($data, $type)
    {

        $query = 'SELECT DISTINCT a FROM FeodBundle:'.ucfirst($type).' a';

        //$qb -> select('m')
        //    -> from('FeodBundle:'.ucfirst($type),'m');
        foreach ($data as $key => $value) {
            if (is_string($value)) {
                $query.= 'a.'.$key.'LIKE %'.$value.'%';
            } elseif ($value instanceof \Doctrine\Common\Collections\ArrayCollection) {
                foreach ($value as $association) {
                    $query.='INDENTITY(a.'.$key.')='.$association;
                }
            } else {
                $query.= 'a.'.$key.'= '.$value.'';
            }
        }

        $result = $this->getEntityManager()
            ->createQuery($query)->getResult();
    }

    public function findByStatutAndType($statut, $type)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb -> select('m')
            -> from('FeodBundle:Amorcage', 'm')
            -> where('m.statut = :statut')
            ->setParameter('statut', $statut);
        if ($type !== 'munition') {
            $qb->andWhere('m INSTANCE OF :type')
            ->setParameter('type', $type);
        }
        $qb-> orderBy('m.dateMAJ', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }

    public function CountByAmorcageId($amorcageId){
        $count = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM FeodBundle:Amorcage a
            WHERE a.amorcageId = :amorcageId')
            ->setParameter('amorcageId', $amorcageId)
            ->getSingleScalarResult();
        return $count;
    }

    public function recherchenomamorcage($chaine)
    {
        $qb = $this->createQueryBuilder('u')
        ->select('u')
        ->where('LOCATE(UPPER(:chaine),UPPER(u.nomine)) != 0')
        ->orwhere('LOCATE(UPPER(:chaine),UPPER(u.denominationOTAN)) != 0')
        ->orwhere('LOCATE(UPPER(:chaine),UPPER(u.alias)) != 0')
        ->orderBy('u.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchepaysamorcage($chaine)
    {
        $qb = $this->createQueryBuilder('u')
        ->select('u')
        ->join('u.pays', 'c')
        ->leftjoin('u.paysAcquereur', 'p')
        ->leftjoin('u.retrouveEn', 'r')
        ->where('LOCATE(UPPER(:chaine),UPPER(c.pays)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(p.pays)) != 0')
        ->orwhere('LOCATE(UPPER(:chaine),UPPER(r.pays)) != 0')
        ->orderBy('u.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchepoidsamorcage($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        
         $qb -> select('a')
        ->from('FeodBundle:Amorcage','a')
        //->where('LOCATE(UPPER(:chaine),UPPER(a.poids)) != 0')
        ->where('a.poids = :chaine')
        ->orwhere('a.PoidsMunCalcule = :chaine')
        ->orderBy('a.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchecouleuramorcage($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        $qb -> select('m')
        ->from('FeodBundle:Amorcage','m')
        ->Join('m.couleurPrincipale', 'v')
        ->leftjoin('m.couleurSecondaire', 'x')
        ->where('LOCATE(UPPER(:chaine),UPPER(v.couleurFond)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(x.couleurFond)) != 0')
        ->orderBy('m.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchecalibreamorcage($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        $qb -> select('m')
        ->from('FeodBundle:Amorcage','m')
        ->where('LOCATE(UPPER(:chaine),UPPER(m.DiametreFusee)) != 0')
        //->orWhere('LOCATE(UPPER(:chaine),UPPER(m.calibreCalcul)) != 0')
        ->orderBy('m.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchedimamorcage($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        $qb -> select('m')
        ->from('FeodBundle:Amorcage','m')
        ->where('LOCATE(UPPER(:chaine),UPPER(m.lgTotavecFusee)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(m.lgTotavecFuseeDouille)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(m.lgTotsansFusee)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(m.hautProjectile)) != 0')
        ->orderBy('m.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function rechercheformeamorcage($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        $qb -> select('m')
        ->from('FeodBundle:Amorcage','m')
        ->Join('m.formeCorps', 'f')
        //->leftjoin('a.couleurOgive', 'x')
        ->where('LOCATE(UPPER(:chaine),UPPER(f.id)) != 0')
        //->orWhere('LOCATE(UPPER(:chaine),UPPER(x.couleurFond)) != 0')
        ->orderBy('m.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }


}
