<?php

namespace FeodBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArtillerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtillerieRepository extends EntityRepository
{

    public function countAll(){
        $count = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM FeodBundle:Artillerie a')
            ->getSingleScalarResult();
        return $count;
    }

    public function CountByMunitionId($munitionId){
        $count = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM FeodBundle:Artillerie a
            WHERE a.munitionId = :munitionId')
            ->setParameter('munitionId', $munitionId)
            ->getSingleScalarResult();
        return $count;
    }

    public function countByStatut($statut){
        $count = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM FeodBundle:Artillerie a
            WHERE a.statut = :statut')
            ->setParameter('statut', $statut)
            ->getSingleScalarResult();
        return $count;
    }

    // Retourne les i dernieres artilleries de la base
    public function findLast($i){
        $qb = $this->_em->createQueryBuilder();

        $qb -> select('a')
            -> from('FeodBundle:Artillerie','a')
            -> where('a.statut = 3')
            -> orderBy('a.dateMAJ','DESC')
            ->setMaxResults($i);

        return $qb->getQuery()
            ->getResult();
    }

     public function recherchenomartillerie($chaine)
    {
        $qb = $this->createQueryBuilder('u')
        ->select('u')
        ->where('LOCATE(UPPER(:chaine),UPPER(u.nomine)) != 0')
        ->orwhere('LOCATE(UPPER(:chaine),UPPER(u.denominationOTAN)) != 0')
        ->orwhere('LOCATE(UPPER(:chaine),UPPER(u.alias)) != 0')
        ->orderBy('u.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchepaysartillerie($chaine)
    {
        $qb = $this->createQueryBuilder('u')
        ->select('u')
        ->join('u.pays', 'c')
        ->leftjoin('u.paysAcquereur', 'p')
        ->leftjoin('u.retrouveEn', 'r')
        ->where('LOCATE(UPPER(:chaine),UPPER(c.pays)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(p.pays)) != 0')
        ->orwhere('LOCATE(UPPER(:chaine),UPPER(r.pays)) != 0')
        ->orderBy('u.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchepoidsartillerie($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        
         $qb -> select('a')
        ->from('FeodBundle:Artillerie','a')
        //->where('LOCATE(UPPER(:chaine),UPPER(a.poids)) != 0')
        ->where('a.poids = :chaine')
        ->orwhere('a.poidsProjectile = :chaine')
        ->orderBy('a.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchecouleurartillerie($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        $qb -> select('m')
        ->from('FeodBundle:Artillerie','m')
        ->Join('m.couleurCorps', 'v')
        //->leftjoin('a.couleurOgive', 'x')
        ->where('LOCATE(UPPER(:chaine),UPPER(v.couleurFond)) != 0')
        //->orWhere('LOCATE(UPPER(:chaine),UPPER(x.couleurFond)) != 0')
        ->orderBy('m.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchecalibreartillerie($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        $qb -> select('m')
        ->from('FeodBundle:Artillerie','m')
        ->where('LOCATE(UPPER(:chaine),UPPER(m.calibre)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(m.calibreCalcul)) != 0')
        ->orderBy('m.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherchedimartillerie($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        $qb -> select('m')
        ->from('FeodBundle:Artillerie','m')
        ->where('LOCATE(UPPER(:chaine),UPPER(m.lgTotavecFusee)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(m.lgTotavecFuseeDouille)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(m.lgTotsansFusee)) != 0')
        ->orWhere('LOCATE(UPPER(:chaine),UPPER(m.hautProjectile)) != 0')
        ->orderBy('m.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
    
    public function rechercheformeartillerie($chaine)
    {

         $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        $qb -> select('m')
        ->from('FeodBundle:Artillerie','m')
        ->Join('m.formeCorps', 'f')
        //->leftjoin('a.couleurOgive', 'x')
        ->where('LOCATE(UPPER(:chaine),UPPER(f.id)) != 0')
        //->orWhere('LOCATE(UPPER(:chaine),UPPER(x.couleurFond)) != 0')
        ->orderBy('m.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()
            ->getResult();
    }
}
