<?php

namespace FeodBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MunitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunitionRepository extends EntityRepository
{

    /**
    * Retourne le nombre de fiches validées
    */
    public function countAll()
    {
        return $this->countByStatut(3);
    }

    /**
    * Retourne le nombre de fiche par statut
    *
    * 0 : modification ou création
    * 1 : attente de vérification
    * 2 : attente de validation
    * 3 : validée
    *
    */
    public function countByStatut($statut)
    {
        $count = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM FeodBundle:Munition a
                WHERE a.statut = :statut')
            ->setParameter('statut', $statut)
            ->getSingleScalarResult();
        return $count;
    }

    public function findLast($i)
    {
        $result = $this->getEntityManager()
            ->createQuery('SELECT a FROM FeodBundle:Munition a
                WHERE a.statut = 3 ORDER BY a.dateMAJ DESC')
            ->setMaxResults($i)
            ->getResult();

        return $result;
    }

    public function countLastMonth()
    {
        $month=new \Datetime();
        $month->sub(new \DateInterval('P1M'));
        $result = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM FeodBundle:Munition a
                WHERE a.dateMAJ <= :auj AND a.dateMAJ > :month')
            ->setParameter('auj', new \Datetime())
            ->setParameter('month', $month)
            ->getSingleScalarResult();

        return $result;
    }



    public function searchByNomAndType($nomine, $type)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb -> select('m')
            -> from('FeodBundle:'.ucfirst($type), 'm');

        if ($nomine != null) {
     $qb->join('m.pays', 'e')
        ->join('m.paysAcquereur', 'p')
        ->where('LOCATE(UPPER(:expression),UPPER(e.pays)) != 0')
        ->orWhere('LOCATE(UPPER(:expression),UPPER(p.pays)) != 0')
        ->orWhere('LOCATE(UPPER(:expression),UPPER(m.nomine)) != 0')
        ->orderBy('m.dateMAJ', 'DESC')
        ->setParameter('expression', $nomine);
        }

        return $qb->getQuery()
            ->getResult();
    }

    public function searchByAll($data, $type)
    {

        $query = 'SELECT DISTINCT a FROM FeodBundle:'.ucfirst($type).' a';

        //$qb -> select('m')
        //    -> from('FeodBundle:'.ucfirst($type),'m');
        foreach ($data as $key => $value) {
            if (is_string($value)) {
                $query.= 'a.'.$key.'LIKE %'.$value.'%';
            } elseif ($value instanceof \Doctrine\Common\Collections\ArrayCollection) {
                foreach ($value as $association) {
                    $query.='INDENTITY(a.'.$key.')='.$association;
                }
            } else {
                $query.= 'a.'.$key.'= '.$value.'';
            }
        }

        $result = $this->getEntityManager()
            ->createQuery($query)->getResult();
    }

    public function findByStatutAndType($statut, $type)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb -> select('m')
            -> from('FeodBundle:Munition', 'm')
            -> where('m.statut = :statut')
            ->setParameter('statut', $statut);
        if ($type !== 'munition') {
            $qb->andWhere('m INSTANCE OF :type')
            ->setParameter('type', $type);
        }
        $qb-> orderBy('m.dateMAJ', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }
    
    public function recherche($chaine)
    {
        $qb = $this->_em->createQueryBuilder();
        //$qb = $this->createQueryBuilder('u');        
        $qb -> select('u')
          -> from('FeodBundle:Munition', 'u')

        //$qb->join('u.pays', 'c')
        //   ->join('u.ExplosifAssocies', 'x')
        //->where('LOCATE(UPPER(:chaine),UPPER(c.pays)) != 0')
        ->Where('LOCATE(UPPER(:chaine),UPPER(u.nomine)) != 0')
        //->orWhere('LOCATE(UPPER(:chaine),UPPER(x.nomine)) != 0')
        ->orderBy('u.dateMAJ', 'DESC')
        ->setParameter('chaine', $chaine);

        
        return $qb->getQuery()
            ->getResult();
    }
    
}
