imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @UserBundle/Resources/config/admin.yml }
    - { resource: @UserBundle/Resources/config/services.yml}


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # other form themes
        - 'FeodBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FeodBundle, UserBundle ]
    #java: /usr/bin/java
    assets:
        chosen_css:
            inputs:
                - "%kernel.root_dir%/../vendor/drmonty/chosen/css/chosen.css"
        chosen_js:
            inputs:
                - "%kernel.root_dir%/../vendor/drmonty/chosen/js/chosen.jquery.js"

    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        lessphp:
             file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
             apply_to: "\.less$"

braincrafted_bootstrap:
    less_filter: lessphp
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.3.min.js
    fonts_dir: %kernel.root_dir%/../web/fonts

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path:     "%database_path%"
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#declaration du fosuserbundle    
fos_user:
    db_driver: orm
    #model_manager_name: cithareEm 
    firewall_name: main
    user_class: UserBundle\Entity\User
    registration:
        form:
            type: feod_user_registration
    change_password:
        form:
            validation_groups: [myChangePassword]
    group:
        group_class: Admin\UserBundle\Entity\Group
        
#fos_user:
#    db_driver: orm
#    firewall_name: main
#    user_class: UserBundle\Entity\User
#    registration:
#        form:
#            type: feod_user_registration

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.back: ~
        # Your other blocks

sonata_admin:
    title:      FEOD
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png
    #security:
    #    handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            # display a dashboard block
            - { position: right, type: sonata.block.service.back }
            - { position: left, type: sonata.admin.block.admin_list }
            #- { position: left, type: sonata.admin.configuration }

vich_uploader:
    db_driver: orm

    mappings:
        munition_image:
            uri_prefix:         uploads
            upload_destination: %kernel.root_dir%/../web/uploads
            namer:              feod.munition_namer
            directory_namer:    feod.directory_namer
            delete_on_remove: true
            
        munition_imageMarquages:
            uri_prefix:         uploads/Marquages
            upload_destination: %kernel.root_dir%/../web/uploads/Marquages
            namer:              feod.munition_namer
            directory_namer:    feod.directory_namer
            
        munition_imageFonctionnement:
            uri_prefix:         uploads/Fonctionnement
            upload_destination: %kernel.root_dir%/../web/uploads/Fonctionnement
            namer:              feod.munition_namer
            directory_namer:    feod.directory_namer
            
        munition_imageConditionnement:
            uri_prefix:         uploads/Conditionnement
            upload_destination: %kernel.root_dir%/../web/uploads/Conditionnement
            namer:              feod.munition_namer
            directory_namer:    feod.directory_namer
            
        munition_imageVecteur:
            uri_prefix:         uploads/Vecteur
            upload_destination: %kernel.root_dir%/../web/uploads/Vecteur
            namer:              feod.munition_namer
            directory_namer:    feod.directory_namer
            
        munition_imageTraitement:
            uri_prefix:         uploads/Traitement
            upload_destination: %kernel.root_dir%/../web/uploads/Traitement
            namer:              feod.munition_namer
            directory_namer:    feod.directory_namer
            
        munition_imageChargement:
            uri_prefix:         uploads/Chargement
            upload_destination: %kernel.root_dir%/../web/uploads/Chargement
            namer:              feod.munition_namer
            directory_namer:    feod.directory_namer
            
        munition_imageDimensions:
            uri_prefix:         uploads/Dimensions
            upload_destination: %kernel.root_dir%/../web/uploads/Dimensions
            namer:              feod.munition_namer
            directory_namer:    feod.directory_namer

        munition_imageFusees:
            uri_prefix:         uploads/FuseesAllumeurs
            upload_destination: %kernel.root_dir%/../web/uploads/FuseesAllumeurs
            namer:              feod.munition_namer
            directory_namer:    feod.directory_namer
            
        amorcage_image:
            uri_prefix:         uploads
            upload_destination: %kernel.root_dir%/../web/uploads
            namer:              feod.amorcage_namer
            directory_namer:    feod.amorcagedirectory_namer
            delete_on_remove: true
            
        amorcage_imageMarquage:
            uri_prefix:         uploads/Marquages
            upload_destination: %kernel.root_dir%/../web/uploads/Marquages
            namer:              feod.amorcage_namer
            directory_namer:    feod.amorcagedirectory_namer
            delete_on_remove: true
            
        amorcage_imageChargement:
            uri_prefix:         uploads/Chargement
            upload_destination: %kernel.root_dir%/../web/uploads/Chargement
            namer:              feod.amorcage_namer
            directory_namer:    feod.amorcagedirectory_namer
            delete_on_remove: true
            
        amorcage_imageDimensions:
            uri_prefix:         uploads/Dimensions
            upload_destination: %kernel.root_dir%/../web/uploads/Dimensions
            namer:              feod.amorcage_namer
            directory_namer:    feod.amorcagedirectory_namer
            delete_on_remove: true
            
        amorcage_imageConditionnement:
            uri_prefix:         uploads/Conditionnement
            upload_destination: %kernel.root_dir%/../web/uploads/Conditionnement
            namer:              feod.amorcage_namer
            directory_namer:    feod.amorcagedirectory_namer
            delete_on_remove: true
            
        amorcage_imageFonctionnement:
            uri_prefix:         uploads/Fonctionnement
            upload_destination: %kernel.root_dir%/../web/uploads/Fonctionnement
            namer:              feod.amorcage_namer
            directory_namer:    feod.amorcagedirectory_namer
            delete_on_remove: true
            
        amorcage_imageVecteur:
            uri_prefix:         uploads/Vecteur
            upload_destination: %kernel.root_dir%/../web/uploads/Vecteur
            namer:              feod.amorcage_namer
            directory_namer:    feod.amorcagedirectory_namer
            delete_on_remove: true
            
        amorcage_imageTraitement:
            uri_prefix:         uploads/Traitement
            upload_destination: %kernel.root_dir%/../web/uploads/Traitement
            namer:              feod.amorcage_namer
            directory_namer:    feod.amorcagedirectory_namer
            delete_on_remove: true

        explosif_ExplosifImage:
            uri_prefix:         uploads
            upload_destination: %kernel.root_dir%/../web/uploads/
            namer:              feod.explosif_namer
            directory_namer:    feod.explosifdirectory_namer
            delete_on_remove: true

        chimique_ChimiqueImage:
            uri_prefix:         uploads
            upload_destination: %kernel.root_dir%/../web/uploads/
            namer:              feod.chimique_namer
            directory_namer:    feod.chimiquedirectory_namer
            delete_on_remove: true
            

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        thumb:
            quality: 100
