security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_CLIENT:      ROLE_USER
        ROLE_EXPERT:      ROLE_CLIENT
        ROLE_VALIDATEUR:  ROLE_EXPERT
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_VALIDATEUR]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path:            /warn
            logout:       true
            anonymous:    true
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js|assetic)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js|assetic), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER}
        - { path: ^/(artillerie|mines|mortier)/$/(create|update), role: ROLE_CLIENT}
